### ISSUE TITLE
Package documentation: Downloading and running MiTfAT

### ISSUE THREAD

**Issue by emdupre** [vahid-sb/MiTfAT#1]
Hi ! Thanks for writing this package and for submitting it to JOSS !

I tried to install MiTfAT and execute the initial example given in your documentation. Specifically, in a new conda environment, I ran `pip install mitfat` which succeeded.

Launching a new python terminal, I ran:

`import mitfat`.

Note that 

```
import `MiTfAT`
```

as suggested in the documentation, fails. I then ran:

```
from mitfat.file_io import read_data
import pkg_resources

info_file = pkg_resources.resource_filename('mitfat', 'sample_info_file.txt')
DATA_PATH = pkg_resources.resource_filename('mitfat', 'datasets')
list_datasets = read_data(info_file)
```

which also fails with the following error.

<details>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emdupre/miniconda3/envs/MiTfAT/lib/python3.6/site-packages/mitfat/file_io.py", line 237, in read_data
    first_trial_time, trial_length = main_get_data(info_file_name)
  File "/home/emdupre/miniconda3/envs/MiTfAT/lib/python3.6/site-packages/mitfat/file_io.py", line 690, in main_get_data
    time_step = read_info_file(info_file_name)
  File "/home/emdupre/miniconda3/envs/MiTfAT/lib/python3.6/site-packages/mitfat/file_io.py", line 412, in read_info_file
    raise Exception('Where is the info file???')
```

</details>

I've confirmed in my file system that these files are not being downloaded with the library, likely because the `setup.py` script (specifically, [here](https://github.com/vahid-sb/MiTfAT/blob/a9dceaf022e815b047dd90da1378ba4512b36b4c/setup.py#L28)) suggests that these files are at the top level when they should be in the `tests` sub-directory.

Correctly packaging these files and updating the documentation appropriately would help in making sure this software is accessible !

**Comment by vahid-sb** [comment]
Hi @emdupre. Thanks for pointing out the typo and the missing data files. Seems mistakenly I have removed a manifest.ini file which is needed to have the data files uploaded with the code. I'd update the code and the manual and will let you know about it when done.

**Comment by vahid-sb** [comment]
Dear @emdupre, I updated the documentation. I added all the sample datasets as a zip file to repo and you can just download, unzip it and run the two scripts. They both should work if mitfat is installed. Please let me know how it goes.

**Comment by emdupre** [comment]
Thanks, @vahid-sb ! I was able to install appropriately and access the `sample_config_file.txt` :+1:  

I'm still not able to access the sample datasets directly in the package. For that, I think you'd need to edit your `setup.py` script.

You could change [this line](https://github.com/vahid-sb/MiTfAT/blob/06fa18950384079f438a0fd6cd1a59f25df3aca7/setup.py#L28) to something like:

```
package_data={
"mitfat": ["sample_info_file.txt"],
"tests": ["*"],
"tests.datasets": ["*"],
"tests.datasets_trials": ["*"]
},
```

But I'd actually encourage you to actually move this directory instead the `mitfat` directory and separate out `tests` (which could contain an inner `data` folder, for data used in testing) from `datasets` (which would contain the datasets used in your examples in the documentation). In which case, the above line could look like:

```
package_data={
"mitfat": ["sample_info_file.txt"],
"mitfat.tests.data": ["*.txt"],
"tests.datasets": ["*.nii.gz", "*.txt"],
"tests.datasets.dataset_trials": ["*.nii.gz", "*.txt"]
},
```

This would help to make sure that it's clear which data is used for internal library testing and which data is related to the documentation / user examples !

**Comment by vahid-sb** [comment]
@emdupre Thanks for your comments. I'd come back to you on them, but very unlikely it'd be this year.

**Comment by emdupre** [comment]
Of course -- I hope they're useful. In the meantime, have a happy holiday season !

**Comment by vahid-sb** [comment]
Yes, they were quite useful. Thanks for that. I'd come back to you on them.

**Comment by vahid-sb** [comment]
Dear @emdupre. Thanks again for your suggestions. I decided to change the manual to refer only to the zip file rather than accompanying the data with the code. The sample datasets change the library size from KBs to tens of MBs, and I prefer to leave it to the user to download the dataset or not.

**Comment by emdupre** [comment]
> I decided to change the manual to refer only to the zip file rather than accompanying the data with the code. The sample datasets change the library size from KBs to tens of MBs, and I prefer to leave it to the user to download the dataset or not.

That makes sense ! I'll follow-up on this in #2, but it might be worth highlighting the example data a bit more prominently in the installation instructions. Since the installation strictly works, though, I'll close this. Thanks for clarifying, here !
