### ISSUE TITLE
Package documentation: User examples

### ISSUE THREAD

**Issue by emdupre** [vahid-sb/MiTfAT#2]
I was reviewing the new user documentation, and I'm having some trouble with sections 3.1 and 3.2 (in "Basics"). 

I assume that the `info_file` in the first 3.1 code block corresponds to `sample_config_file.txt`. But if I try to execute:

```
list_of_datasets = read_data(info_file)
```

I get the following error:

```
Config file: sample_config_file.txt
Current directory: /home/emdupre
Source folder you have given me:
 /home/emdupre/datasets
An exception has occurred, use %tb to see the full traceback.

SystemExit: Source folder DOES NOT exist! :/
```

I imagine the recommended path forward would be downloading `tests.zip` and placing it in the `datasets` folder, but it would be helpful if the documentation was explicit about this. Pending #1, I imagine even be inferred from the package directory, which would definitely help to quickly get new users running on sample data !

Alternatively, just reorganizing the documentation to explain the config file and which values should be changed before loading the data would be helpful for orienting new users.

**Comment by vahid-sb** [comment]
That filename should have been the name of the text file, which I changed in the manual. But that part is simply a very generic example. I have rearranged that chapter and made it (hopefully) easier to read and brought the discussions on the sample dataset to a new subsection to make things more organized.

**Comment by emdupre** [comment]
Thanks, @vahid-sb ! I'm able to run things much more smoothly now. I still am hitting a few stumbling blocks when following the docs that are worth addressing:

-  The first code blocks fails in section 3.1. I know that this is because it is only intended as an example, but I would argue that having the code blocks succeed is reasonably important ! I worry that the failure is likely to confuse users -- and you define an actual, usable filename just two sections down. I would recommend moving the `from mitfat.io import read_data` block into section 3.2 after you mention how to access the dataset.
- Chapter 4 onwards assumes we have a variable called `dataset1`, while Chapter 3 only defines`my_first_dataset`. This is small, but again will likely cause first user attempts to fail

**Comment by vahid-sb** [comment]
Thanks for your diligence in checking such details in the manual. I changed Section 3.1 code to what is written in the sample script. So, it will load the sample dataset assuming the working directory is set to where the files are. Also, dataset1 is what is defined in Section 3.1 and clarified that in the future chapter, the variable refers to what is defined in Section 3.1.

**Comment by emdupre** [comment]
Great, thank you @vahid-sb ! I think this will help users to quickly orient to your tool -- I'm excited to see what they'll do with it ! :rocket:
